### PR TITLE
Guard Level Design Prototype created by Brett

### PR DESCRIPTION
**Pull request by bam4**
This is a prototype of the Guard Level Design created on August 3rd.

### CODE REVIEW

**Comment by mzguimaraes** [comment]
Only changes in meta file--looks good to me!

**Comment by mikeathal** [comment]
If Marcus is fine with it then so am I!  He knows everything!

**Comment by GhostatSpirit** [comment]
Unity version metadata seems to have changed.

**Comment by mzguimaraes** [comment]
Yeah we've updated Unity since I started the project.  Are you on 5.4 Yang?

Sandals

**Pull request merged**
